import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:ledgr/core/go_router/app_router.dart';
import 'package:ledgr/features/budget/data/models/budget_model.dart';
import 'core/di/injection_container.dart';
import 'features/transactions/data/models/transaction_model.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  ServicesBinding.instance.keyboard.syncKeyboardState();

  await Hive.initFlutter();
  Hive.registerAdapter(TransactionModelAdapter()); // generated by build_runner
  Hive.registerAdapter(BudgetModelAdapter()); // add this

  final overrides = await initDependencies();

  runApp(
    ProviderScope(
      overrides: overrides,
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      title: 'Ledgr',
      routerConfig: appRouter,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF1D9E75)),
        useMaterial3: true,
      ),
    );
  }
}